name: Build and Update to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'  # Ensure this matches the Node version you want

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build
      env:
        NODE_OPTIONS: --openssl-legacy-provider # If dealing with the OpenSSL issue

    - name: Commit build artifacts
      run: |
        git config --local user.email "s.m.d.thiranjaya@gmail.com"
        git config --local user.name "smdthiranjaya"
        git add build -f
        git commit -m "Deploy Build Artifacts" --allow-empty
        git push
